trigger:
- main  # O la rama que desees

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '3.x'  # O la versión de .NET que estás utilizando

  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'

  - task: DotNetCoreCLI@2
    displayName: 'Build Backend'
    inputs:
      command: 'build'
      arguments: '--configuration Release'

  - task: Docker@2
    displayName: 'Build Backend Docker image'
    inputs:
      command: 'build'
      repository: 'backend'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: '$(Build.BuildId)'

  # Agrega tareas adicionales según sea necesario, como pruebas unitarias, pruebas de integración, etc.

  - task: Docker@2
    displayName: 'Build Database Docker image'
    inputs:
      command: 'build'
      repository: 'database'
      Dockerfile: '$(Build.SourcesDirectory)/mysql_docker/Dockerfile'
      tags: '$(Build.BuildId)'
