trigger:
  branches:
    include:
      - development

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: Docker@2
    displayName: 'Build Docker images'
    inputs:
      command: 'build'
      repository: 'backend'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: '$(Build.BuildId)'

  - task: Docker@2
    displayName: 'Build Database Docker image'
    inputs:
      command: 'build'
      repository: 'database'
      Dockerfile: '$(Build.SourcesDirectory)/mysql_docker/Dockerfile'
      tags: '$(Build.BuildId)'

  - script: |
      pip install -r requirements.txt
      python -m unittest app_test.py
    displayName: 'Run Unit Tests'